version: '3.7'
services:
  db:
    image: mysql
    container_name: realmysql
    volumes:
    - ~/docker/volume/TestDatabase-Employee:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1323
    ports:
    - 3306:3306